### PR TITLE
install instructions

### PR DESCRIPTION
**Pull request by ThomasLecocq**
conda-forge 's fortran-compiler is clever :)

### CODE REVIEW

**Comment by trichter** [comment]
I was two minutes faster ;)

Here is the link to the travis fail:

https://travis-ci.org/trichter/toeplitz/jobs/656179805

```
ImportError: DLL load failed: The specified module could not be found.
```


Can you make something out of it?

It appears to me, the fortran compiler of chocolatery is used. Maybe that is the problem?

**Comment by ThomasLecocq** [comment]
this happens when I activate the envs now (since installing the fortran stuff, I think):

```
(rfenv37) λ conda activate rfenv

set "LIB="

set "CPATH="

set "_LIB="

set "_CPATH="

if "c:\ProgramData\Anaconda3\envs\rfenv" == "" set "LIB=;\Library\lib"

if "c:\ProgramData\Anaconda3\envs\rfenv" == "" set "CPATH=;\Library\include"

if not "c:\ProgramData\Anaconda3\envs\rfenv" == "" set "LIB=;c:\ProgramData\Anaconda3\envs\rfenv\Library\lib"

if not "c:\ProgramData\Anaconda3\envs\rfenv" == "" set "CPATH=;c:\ProgramData\Anaconda3\envs\rfenv\Library\include"
```
automagically... but it doesn't seem to be there on your travis

```
(rfenv) λ conda --version
conda 4.8.2
```

**Comment by ThomasLecocq** [comment]
> ``It appears to me, the fortran compiler of chocolatery is used. Maybe that is the problem?``

that yep, I have no idea what it does

**Comment by ThomasLecocq** [comment]
on my machine, it says:

``` Found executable C:\ProgramData\Anaconda3\envs\toeplenv\Library\bin\flang.exe```

when building the package. So it's most probably a PATH issue on travis.

**Comment by ThomasLecocq** [comment]
you can call

```
- %CONDA_PREFIX%\\etc\\conda\\activate.d\\flang_activate.bat
- %CONDA_PREFIX%\\etc\\conda\\activate.d\\proj4-activate.bat
```
manually ?

**Comment by trichter** [comment]
You think this could help?
I started with displaying the path variable in #4.

**Comment by trichter** [comment]
I do not know why travis is not triggered for this branch...

Contents of PATH are
```
> echo $PATH
C:/miniconda:
C:/miniconda/Library/mingw-w64/bin:
C:/miniconda/Library/usr/bin:
C:/miniconda/Library/bin:
C:/miniconda/Scripts:
C:/miniconda/bin:
/c/miniconda/envs/testenv:
/c/miniconda/envs/testenv/Library/mingw-w64/bin:
/c/miniconda/envs/testenv/Library/usr/bin:
/c/miniconda/envs/testenv/Library/bin:
/c/miniconda/envs/testenv/Scripts:
/c/miniconda/envs/testenv/bin:
C:/miniconda:C:/miniconda/Library/mingw-w64/bin:
C:/miniconda/Library/usr/bin:
C:/miniconda/Library/bin:
C:/miniconda/Scripts:
C:/miniconda/bin:
C:/miniconda/Scripts/condabin:
/usr/bin:
/usr/bin:
/c/tools/ruby27/bin:
/c/Windows/system32:
/c/Windows:
/c/Windows/System32/Wbem:
/c/Windows/System32/WindowsPowerShell/v1.0:
/c/Windows/System32/OpenSSH:
/c/ProgramData/GooGet:
/c/Program Files/Google/Compute Engine/metadata_scripts:
/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:
/c/Program Files/Google/Compute Engine/sysprep:
/c/Program Files/Docker:/c/ProgramData/chocolatey/bin:
/c/Program Files/CMake/bin:
/c/Program Files/Git/cmd:
/c/Program Files/LLVM/bin:
/c/Program Files/dotnet:
/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:
/c/tools/BCURRAN3:
/c/Users/travis/AppData/Local/Microsoft/WindowsApps:
/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin
```

**Comment by trichter** [comment]
> If a pull request isn’t built or doesn’t show up in Travis CI’s user interface, that usually means that it can’t be merged.

**Comment by trichter** [comment]
Fixed in trichter/conda4travis#2

**Pull request closed without merging**
