### PR TITLE
activate conda rc configs manually

### PR DESCRIPTION
**Pull request by ThomasLecocq**
sync'd with upstream now

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
continuation of https://github.com/trichter/toeplitz/pull/2

**Comment by ThomasLecocq** [comment]
I don't understand why travis doesn't work here?

**Comment by trichter** [comment]
I also don't understand it. The settings for the repository are also OK. As a work-around you could activate it in your own travis account.

**Comment by ThomasLecocq** [comment]
I think travis' webhooks are down

**Comment by trichter** [comment]
It's working for PR #4, but this is also located inside the main repository.

**Comment by trichter** [comment]
#4 is working now.
For me this work-around is good enough.

Thank you!

**Comment by ThomasLecocq** [comment]
:-) top

**Pull request closed without merging**
